

FROM finsberg/fenics:latest

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install h5py --no-binary=h5py

RUN python3 -m pip install black \
    bump2version \
    coverage \
    flake8 \
    ipython \
    ipywidgets \
    isort  \
    myst-nb \
    myst-parser \
    mypy \
    nbsphinx \
    pandoc \
    pre-commit \
    pytest \
    pytest-cov \
    pytest-sugar \
    Sphinx \
    tox \
    wheel \
    jupytext \
    jupyter-book \
    daiquiri \
    scipy \
    gmsh \
    meshio \
    matplotlib \
    plotly
